from app.models import db, User, Friendship

def seed_friends():
  users = User.query.all()

  demo = Friendship(user_id=users[0].id, friend_id=users[1].id)
  demo1 = Friendship(user_id=users[0].id, friend_id=users[2].id)
  demo2 = Friendship(user_id=users[0].id, friend_id=users[3].id)
  demo3 = Friendship(user_id=users[0].id, friend_id=users[4].id)
  demo4 = Friendship(user_id=users[0].id, friend_id=users[5].id)
  demo5 = Friendship(user_id=users[0].id, friend_id=users[6].id)
  demo6 = Friendship(user_id=users[0].id, friend_id=users[7].id)
  demo7 = Friendship(user_id=users[0].id, friend_id=users[8].id)
  demo8 = Friendship(user_id=users[0].id, friend_id=users[9].id)
  demo9 = Friendship(user_id=users[0].id, friend_id=users[10].id)
  demo10 = Friendship(user_id=users[0].id, friend_id=users[11].id)
  demo11 = Friendship(user_id=users[1].id, friend_id=users[0].id)
  demo12 = Friendship(user_id=users[2].id, friend_id=users[0].id)
  demo13 = Friendship(user_id=users[3].id, friend_id=users[0].id)
  demo14 = Friendship(user_id=users[4].id, friend_id=users[0].id)
  demo15 = Friendship(user_id=users[5].id, friend_id=users[0].id)
  demo16 = Friendship(user_id=users[6].id, friend_id=users[0].id)
  demo17 = Friendship(user_id=users[7].id, friend_id=users[0].id)
  demo18 = Friendship(user_id=users[8].id, friend_id=users[0].id)
  demo19 = Friendship(user_id=users[9].id, friend_id=users[0].id)
  demo20 = Friendship(user_id=users[10].id, friend_id=users[0].id)
  demo21 = Friendship(user_id=users[11].id, friend_id=users[0].id)

  db.session.add(demo)
  db.session.add(demo1)
  db.session.add(demo2)
  db.session.add(demo3)
  db.session.add(demo4)
  db.session.add(demo5)
  db.session.add(demo6)
  db.session.add(demo7)
  db.session.add(demo8)
  db.session.add(demo9)
  db.session.add(demo10)
  db.session.add(demo11)
  db.session.add(demo12)
  db.session.add(demo13)
  db.session.add(demo14)
  db.session.add(demo15)
  db.session.add(demo16)
  db.session.add(demo17)
  db.session.add(demo18)
  db.session.add(demo19)
  db.session.add(demo20)
  db.session.add(demo21)

  db.session.commit()


def undo_friends():
  db.session.execute('TRUNCATE friendships CASCADE;')
  db.session.commit()